<script setup lang="ts">
import { onMounted, ref } from "vue";
import { adminApi, type AdminAccount, type Page } from "@/api/admin";

const page = ref<Page<AdminAccount>>({ items: [], total: 0, page: 1, pageSize: 20, pageCount: 0 });
const query = ref(""); const status = ref(""); const loading = ref(false); const error = ref("");
async function load() { loading.value = true; error.value = ""; try { page.value = await adminApi.admins({ query: query.value, status: status.value, page: page.value.page, pageSize: page.value.pageSize }); } catch (e) { error.value = e instanceof Error ? e.message : "加载失败"; } finally { loading.value = false; } }
async function toggle(item: AdminAccount) { const reason = window.prompt(item.status === "ACTIVE" ? "请输入停用原因" : "请输入启用原因"); if (!reason) return; try { await adminApi.updateAdmin(item.id, { displayName: item.displayName, status: item.status === "ACTIVE" ? "DISABLED" : "ACTIVE", reason, version: item.version }); await load(); } catch (e) { error.value = e instanceof Error ? e.message : "更新失败"; } }
onMounted(load);
</script>
<template><section class="admin-page"><header class="admin-page-header"><div><p class="admin-page-kicker">平台治理</p><h1>管理员账号</h1><p>管理管理员状态、角色和会话。</p></div><button class="admin-icon-button bordered" type="button" @click="load">刷新</button></header><form class="admin-filter-bar" @submit.prevent="page.page = 1; load()"><input v-model="query" placeholder="手机号或显示名" /><select v-model="status"><option value="">全部状态</option><option value="ACTIVE">启用</option><option value="DISABLED">停用</option></select><button class="admin-action-button" type="submit">搜索</button></form><p v-if="error" class="admin-error">{{ error }}</p><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>管理员</th><th>状态</th><th>角色</th><th>最近登录</th><th>版本</th><th>操作</th></tr></thead><tbody><tr v-for="item in page.items" :key="item.id"><td><strong>{{ item.displayName }}</strong><small>{{ item.phoneMasked }}</small></td><td>{{ item.status === "ACTIVE" ? "启用" : "停用" }}</td><td>{{ item.role }}</td><td>{{ item.lastLoginAt ? new Date(item.lastLoginAt).toLocaleString() : "-" }}</td><td>{{ item.version }}</td><td><button class="admin-text-button" type="button" @click="toggle(item)">{{ item.status === "ACTIVE" ? "停用" : "启用" }}</button></td></tr><tr v-if="!loading && !page.items.length"><td colspan="6">暂无管理员</td></tr></tbody></table></div></section></template>
