<script setup lang="ts">
import { onMounted, ref } from "vue";
import { adminApi, type BillingOrder, type Page } from "@/api/admin";
const page = ref<Page<BillingOrder>>({ items: [], total: 0, page: 1, pageSize: 20, pageCount: 0 });
const status = ref(""); const query = ref(""); const loading = ref(false); const error = ref("");
async function load() { loading.value = true; error.value = ""; try { page.value = await adminApi.orders({ status: status.value, query: query.value, page: page.value.page, pageSize: page.value.pageSize }); } catch (e) { error.value = e instanceof Error ? e.message : "加载失败"; } finally { loading.value = false; } }
async function refund(order: BillingOrder) { const reason = window.prompt("退款原因"); if (!reason) return; try { await adminApi.refund(order.orderNo, reason, `refund-${order.orderNo}-${Date.now()}`); await load(); } catch (e) { error.value = e instanceof Error ? e.message : "退款失败"; } }
onMounted(load);
</script>
<template><section class="admin-page"><header class="admin-page-header"><div><p class="admin-page-kicker">资金与额度</p><h1>支付订单</h1><p>查询支付状态和处理未消费订单的全额退款。</p></div><button class="admin-action-button" type="button" @click="load">刷新</button></header><form class="admin-filter-bar" @submit.prevent="page.page = 1; load()"><input v-model="query" placeholder="订单号或手机号" /><select v-model="status"><option value="">全部状态</option><option>CREATED</option><option>PAID</option><option>REFUNDED</option><option>CANCELLED</option></select><button class="admin-action-button" type="submit">查询</button></form><p v-if="error" class="admin-error">{{ error }}</p><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>订单</th><th>用户</th><th>产品</th><th>金额</th><th>状态</th><th>创建时间</th><th /></tr></thead><tbody><tr v-for="item in page.items" :key="item.orderNo"><td>{{ item.orderNo }}<small>{{ item.provider }}</small></td><td>{{ item.phoneMasked }}</td><td>{{ item.productName }} × {{ item.quantity }}<small>{{ item.creditAmount }} 点</small></td><td>{{ (item.amountMinor / 100).toFixed(2) }} {{ item.currency }}</td><td>{{ item.status }}</td><td>{{ new Date(item.createdAt).toLocaleString() }}</td><td><button v-if="item.status === 'PAID'" class="admin-link-button" type="button" @click="refund(item)">退款</button></td></tr><tr v-if="!loading && !page.items.length"><td colspan="7">暂无订单</td></tr></tbody></table></div></section></template>
