<script setup lang="ts">
import { onMounted, ref } from "vue";
import { adminApi, type AdminPermissionDefinition, type AdminRoleDefinition } from "@/api/admin";
const roles = ref<AdminRoleDefinition[]>([]); const permissions = ref<AdminPermissionDefinition[]>([]); const error = ref(""); const selected = ref<AdminRoleDefinition | null>(null); const saving = ref(false);
async function load() { try { [roles.value, permissions.value] = await Promise.all([adminApi.roles(), adminApi.permissions()]); selected.value ||= roles.value[0] || null; } catch (e) { error.value = e instanceof Error ? e.message : "加载失败"; } }
function pick(role: AdminRoleDefinition) { selected.value = role; }
function checked(id: string) { return !!selected.value?.permissionIds.includes(id); }
async function save() { if (!selected.value || selected.value.system) return; const ids = permissions.value.filter((p) => checked(p.id)).map((p) => p.id); const reason = window.prompt("请输入权限变更原因"); if (!reason) return; saving.value = true; try { selected.value = await adminApi.replaceRolePermissions(selected.value.id, ids, reason, selected.value.version); await load(); } catch (e) { error.value = e instanceof Error ? e.message : "保存失败"; } finally { saving.value = false; } }
onMounted(load);
</script>
<template><section class="admin-page"><header class="admin-page-header"><div><p class="admin-page-kicker">平台治理</p><h1>角色与权限</h1><p>查看系统角色并配置自定义角色的权限矩阵。</p></div><button class="admin-icon-button bordered" type="button" @click="load">刷新</button></header><p v-if="error" class="admin-error">{{ error }}</p><div class="admin-split-layout"><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>角色</th><th>账号</th><th>权限</th></tr></thead><tbody><tr v-for="role in roles" :key="role.id" :class="{ 'is-selected': selected?.id === role.id }" @click="pick(role)"><td><strong>{{ role.name }}</strong><small>{{ role.code }}{{ role.system ? " · 系统" : "" }}</small></td><td>{{ role.accountCount }}</td><td>{{ role.permissionCount }}</td></tr></tbody></table></div><aside class="admin-panel"><h2>{{ selected?.name || "选择角色" }}</h2><p v-if="selected">{{ selected.description || "暂无描述" }}</p><fieldset v-if="selected" class="permission-grid"><label v-for="permission in permissions" :key="permission.id"><input type="checkbox" :checked="checked(permission.id)" :disabled="selected.system" @change="selected && (selected.permissionIds = checked(permission.id) ? selected.permissionIds.filter((id) => id !== permission.id) : [...selected.permissionIds, permission.id])" /><span>{{ permission.code }}</span></label></fieldset><button v-if="selected && !selected.system" class="admin-action-button" type="button" :disabled="saving" @click="save">保存权限</button></aside></div></section></template>
