packages:
  - apps/*
  - packages/*

allowBuilds:
  "@prisma/engines": true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: true
minimumReleaseAgeExclude:
  - bullmq@6.0.5
  - ioredis@6.0.0
