<script setup lang="ts">
import { LoaderCircle, X } from "lucide-vue-next";
import { computed, onMounted, onUnmounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import { api } from "@/api/client";
import { useAuthStore } from "@/stores/auth";
const router = useRouter(); const route = useRoute(); const auth = useAuthStore(); const email = ref(""); const password = ref(""); const code = ref(""); const challengeId = ref(""); const cooldown = ref(0); const loading = ref(false); const sending = ref(false); const agreed = ref(false); const error = ref(""); let timer = 0;
const validEmail = computed(() => /^[^@\s]+@(qq\.com|163\.com|foxmail\.com)$/i.test(email.value.trim())); const returnTo = computed(() => { const value = String(route.query.returnTo || "/inspiration"); return value.startsWith("/") && !value.startsWith("//") && !value.includes("\\") ? value : "/inspiration"; });
async function sendCode() { if (!validEmail.value) { error.value = "请输入 qq.com、163.com 或 foxmail.com 邮箱"; return; } sending.value = true; error.value = ""; try { const result = await api.registrationCode(email.value.trim().toLowerCase()); challengeId.value = result.challengeId; cooldown.value = result.retryAfterSeconds || 60; } catch (e) { error.value = e instanceof Error ? e.message : "邮箱验证码发送失败"; } finally { sending.value = false; } }
async function submit() { if (!validEmail.value || password.value.length < 8 || password.value.length > 72 || code.value.length !== 6 || !challengeId.value || !agreed.value) return; loading.value = true; error.value = ""; try { await auth.register({ email: email.value.trim().toLowerCase(), challengeId: challengeId.value, emailCode: code.value, password: password.value, version: "2026-01", termsAccepted: true, privacyAccepted: true, aiTermsAccepted: true }); await router.replace(returnTo.value); } catch (e) { error.value = e instanceof Error ? e.message : "注册失败"; } finally { loading.value = false; } }
onMounted(() => { timer = window.setInterval(() => { if (cooldown.value > 0) cooldown.value -= 1; }, 1000); }); onUnmounted(() => window.clearInterval(timer));
</script>
<template><main class="login-page"><section class="login-visual" aria-label="Dream Space brand visual"><div class="login-scene" aria-hidden="true" /><div class="login-brand"><span class="brand-mark" /><span class="login-brand-copy"><strong>造梦空间 · Dream Space</strong><small>AI IMAGE STUDIO</small></span></div></section><section class="login-form-wrap"><button class="icon-btn login-close" type="button" aria-label="关闭注册" @click="router.replace(returnTo)"><X aria-hidden="true" /></button><form class="login-form" @submit.prevent="submit"><h1>创建造梦空间账号</h1><p class="login-subtitle">用邮箱验证后开始你的图片创作。</p><label class="form-label" for="registerEmail">邮箱地址</label><input id="registerEmail" v-model="email" class="form-input" type="email" autocomplete="email" placeholder="qq.com / 163.com / foxmail.com" maxlength="254" /><label class="form-label" for="registerPassword">密码</label><input id="registerPassword" v-model="password" class="form-input" type="password" autocomplete="new-password" maxlength="72" /><label class="form-label" for="registerCode">邮箱验证码</label><div class="code-row"><input id="registerCode" v-model="code" class="form-input" inputmode="numeric" autocomplete="one-time-code" maxlength="6" @input="code = code.replace(/\D/g, '').slice(0, 6)" /><button class="action-btn code-send" type="button" :disabled="sending || cooldown > 0" @click="sendCode"><LoaderCircle v-if="sending" class="spin" aria-hidden="true" />{{ cooldown > 0 ? `${cooldown}s` : "发送验证码" }}</button></div><label class="agreement"><input v-model="agreed" type="checkbox" /><span>我已阅读并同意用户协议、隐私政策和 AI 功能使用协议。</span></label><div class="login-error" role="alert">{{ error }}</div><button class="action-btn primary login-submit" type="submit" :disabled="loading || !validEmail || password.length < 8 || code.length !== 6 || !challengeId || !agreed"><LoaderCircle v-if="loading" class="spin" aria-hidden="true" />注册并继续</button><button class="text-link" type="button" @click="router.replace({ path: '/login', query: route.query })">已有账号？登录</button></form></section></main></template>
