package com.dreamspace.api.persistence.admin;

import java.time.Instant;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

@Mapper
public interface BillingMapper {
  String USER_SELECT = "SELECT u.\"id\",u.\"phone\",u.\"status\",u.\"displayName\",u.\"createdAt\",u.\"lastLoginAt\",u.\"disabledAt\",u.\"disabledReason\" FROM \"User\" u";
  String LEDGER_SELECT = "SELECT \"id\",\"userId\",\"taskId\",\"type\",\"amount\",\"balanceAfter\",\"sourceType\",\"sourceId\",\"ruleId\",\"ruleVersion\",\"reasonCode\",\"createdAt\" FROM \"QuotaLedgerEntry\"";
  // PostgreSQL cannot infer the type of a nullable bind parameter used directly in IS NULL.
  String LEDGER_TYPE_FILTER = "(CAST(#{type} AS \"QuotaLedgerType\") IS NULL OR \"type\"=CAST(#{type} AS \"QuotaLedgerType\"))";

  @Select(USER_SELECT + " WHERE u.\"id\"=#{id} LIMIT 1") BillingUserRecord findUser(String id);
  @Select(USER_SELECT + " WHERE (#{query} IS NULL OR u.\"phone\" LIKE CONCAT('%',#{query},'%') OR LOWER(COALESCE(u.\"displayName\",'')) LIKE LOWER(CONCAT('%',#{query},'%'))) ORDER BY u.\"createdAt\" DESC LIMIT #{limit} OFFSET #{offset}")
  List<BillingUserRecord> listUsers(@Param("query") String query, @Param("limit") int limit, @Param("offset") int offset);
  @Select("SELECT COUNT(*) FROM \"User\" u WHERE (#{query} IS NULL OR u.\"phone\" LIKE CONCAT('%',#{query},'%') OR LOWER(COALESCE(u.\"displayName\",'')) LIKE LOWER(CONCAT('%',#{query},'%')))")
  long countUsers(@Param("query") String query);
  @Select("SELECT COUNT(*) FROM \"UserSession\" WHERE \"userId\"=#{id}") long countSessions(String id);
  @Update("UPDATE \"User\" SET \"status\"='DISABLED',\"disabledAt\"=CURRENT_TIMESTAMP,\"disabledBy\"=#{actorId},\"disabledReason\"=#{reason},\"updatedAt\"=CURRENT_TIMESTAMP WHERE \"id\"=#{id} AND \"status\"='ACTIVE'")
  int disableUser(@Param("id") String id, @Param("actorId") String actorId, @Param("reason") String reason);
  @Update("UPDATE \"User\" SET \"status\"='ACTIVE',\"disabledAt\"=NULL,\"disabledBy\"=NULL,\"disabledReason\"=NULL,\"updatedAt\"=CURRENT_TIMESTAMP WHERE \"id\"=#{id} AND \"status\"='DISABLED'") int enableUser(String id);
  @Update("DELETE FROM \"UserSession\" WHERE \"userId\"=#{id}") int revokeSessions(String id);
  @Update("UPDATE \"User\" SET \"displayName\"=#{displayName},\"updatedAt\"=CURRENT_TIMESTAMP WHERE \"id\"=#{id}") int updateDisplayName(@Param("id") String id, @Param("displayName") String displayName);
  @Select(LEDGER_SELECT + " WHERE \"userId\"=#{userId} AND " + LEDGER_TYPE_FILTER + " ORDER BY \"createdAt\" DESC LIMIT #{limit} OFFSET #{offset}")
  List<BillingLedgerRecord> listLedger(@Param("userId") String userId, @Param("type") String type, @Param("limit") int limit, @Param("offset") int offset);
  @Select("SELECT COUNT(*) FROM \"QuotaLedgerEntry\" WHERE \"userId\"=#{userId} AND " + LEDGER_TYPE_FILTER) long countLedger(@Param("userId") String userId, @Param("type") String type);
  @Select("SELECT COUNT(*) FROM \"QuotaLedgerEntry\" WHERE \"userId\"=#{userId} AND " + LEDGER_TYPE_FILTER) long countUserLedger(@Param("userId") String userId, @Param("type") String type);
  @Insert("INSERT INTO \"QuotaLedgerEntry\" (\"id\",\"userId\",\"type\",\"amount\",\"balanceAfter\",\"idempotencyKey\",\"sourceType\",\"sourceId\",\"reasonCode\",\"createdAt\") SELECT #{id},a.\"userId\",'GRANT'::\"QuotaLedgerType\",#{amount},a.\"available\"+#{amount},#{key},#{sourceType},#{sourceId},#{reason},CURRENT_TIMESTAMP FROM \"QuotaAccount\" a WHERE a.\"userId\"=#{userId} ON CONFLICT (\"idempotencyKey\") DO NOTHING")
  int insertGrant(@Param("id") String id, @Param("userId") String userId, @Param("amount") int amount, @Param("key") String key, @Param("sourceType") String sourceType, @Param("sourceId") String sourceId, @Param("reason") String reason);
  @Select("SELECT COUNT(*) FROM \"QuotaLedgerEntry\" WHERE \"userId\"=#{userId} AND \"type\"='GRANT'::\"QuotaLedgerType\"") int countGrants(String userId);
  @Insert("INSERT INTO \"BillingAuditEvent\" (\"id\",\"actorId\",\"actorType\",\"action\",\"subjectType\",\"subjectId\",\"beforeJson\",\"afterJson\",\"reason\",\"createdAt\") VALUES (#{id},#{actorId},#{actorType},#{action},#{subjectType},#{subjectId},CAST(#{beforeJson} AS JSONB),CAST(#{afterJson} AS JSONB),#{reason},CURRENT_TIMESTAMP)")
  int insertAudit(@Param("id") String id, @Param("actorId") String actorId, @Param("actorType") String actorType,
      @Param("action") String action, @Param("subjectType") String subjectType, @Param("subjectId") String subjectId,
      @Param("beforeJson") String beforeJson, @Param("afterJson") String afterJson, @Param("reason") String reason);
  @Select("SELECT \"id\",\"code\",\"version\",\"operation\",\"modelPattern\",\"resolution\",\"minWidth\",\"maxWidth\",\"minHeight\",\"maxHeight\",\"unitCreditCost\",\"formula\",\"effectiveFrom\",\"effectiveTo\",\"status\",\"createdBy\",\"createdAt\",\"updatedAt\" FROM \"PricingRule\" ORDER BY \"operation\",\"version\" DESC") List<PricingRuleRecord> listPricingRules();
  @Select("SELECT \"id\",\"code\",\"version\",\"operation\",\"modelPattern\",\"resolution\",\"minWidth\",\"maxWidth\",\"minHeight\",\"maxHeight\",\"unitCreditCost\",\"formula\",\"effectiveFrom\",\"effectiveTo\",\"status\",\"createdBy\",\"createdAt\",\"updatedAt\" FROM \"PricingRule\" WHERE \"operation\"=#{operation} AND \"status\"='ACTIVE' AND \"effectiveFrom\"<=CURRENT_TIMESTAMP AND (\"effectiveTo\" IS NULL OR \"effectiveTo\">CURRENT_TIMESTAMP) AND (\"resolution\"='ANY' OR \"resolution\"=#{resolution}) ORDER BY \"version\" DESC LIMIT 1") PricingRuleRecord findActivePricingRule(@Param("operation") String operation, @Param("resolution") String resolution);
  @Insert("INSERT INTO \"PricingRule\" (\"id\",\"code\",\"version\",\"operation\",\"modelPattern\",\"resolution\",\"minWidth\",\"maxWidth\",\"minHeight\",\"maxHeight\",\"unitCreditCost\",\"formula\",\"effectiveFrom\",\"effectiveTo\",\"status\",\"createdBy\",\"createdAt\",\"updatedAt\") VALUES (#{id},#{code},#{version},#{operation},#{modelPattern},#{resolution},#{minWidth},#{maxWidth},#{minHeight},#{maxHeight},#{unitCreditCost},#{formula},#{effectiveFrom},#{effectiveTo},'DRAFT',#{createdBy},CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)") int insertPricingRule(PricingRuleRecord rule);
  @Update("UPDATE \"PricingRule\" SET \"status\"=#{status},\"effectiveFrom\"=#{effectiveFrom},\"updatedAt\"=CURRENT_TIMESTAMP WHERE \"id\"=#{id} AND \"status\"=#{expectedStatus}") int updatePricingStatus(@Param("id") String id, @Param("status") String status, @Param("expectedStatus") String expectedStatus, @Param("effectiveFrom") Instant effectiveFrom);
  @Select("SELECT \"id\",\"code\",\"name\",\"creditAmount\",\"amountMinor\",\"currency\",\"validityDays\",\"status\",\"sortOrder\",\"createdAt\",\"updatedAt\" FROM \"CreditProduct\" WHERE \"status\"='ACTIVE' ORDER BY \"sortOrder\",\"id\"") List<CreditProductRecord> listActiveProducts();
  @Select("SELECT \"id\",\"code\",\"name\",\"creditAmount\",\"amountMinor\",\"currency\",\"validityDays\",\"status\",\"sortOrder\",\"createdAt\",\"updatedAt\" FROM \"CreditProduct\" ORDER BY \"sortOrder\",\"id\"") List<CreditProductRecord> listAllProducts();
  String ORDER_SELECT = "SELECT \"id\",\"orderNo\",\"userId\",\"productId\",\"productCode\",\"productName\",\"quantity\",\"creditAmount\",\"amountMinor\",\"currency\",\"status\",\"provider\",\"idempotencyKey\",\"expiresAt\",\"paidAt\",\"createdAt\",\"updatedAt\" FROM \"BillingOrder\"";
  @Select("SELECT \"id\",\"code\",\"name\",\"creditAmount\",\"amountMinor\",\"currency\",\"validityDays\",\"status\",\"sortOrder\",\"createdAt\",\"updatedAt\" FROM \"CreditProduct\" WHERE \"id\"=#{id} LIMIT 1") CreditProductRecord findProduct(String id);
  @Select(ORDER_SELECT + " WHERE \"userId\"=#{userId} AND \"idempotencyKey\"=#{key} LIMIT 1") BillingOrderRecord findOrderByKey(@Param("userId") String userId, @Param("key") String key);
  @Select(ORDER_SELECT + " WHERE \"orderNo\"=#{orderNo} AND \"userId\"=#{userId} LIMIT 1") BillingOrderRecord findOrder(@Param("userId") String userId, @Param("orderNo") String orderNo);
  @Select(ORDER_SELECT + " WHERE \"orderNo\"=#{orderNo} LIMIT 1") BillingOrderRecord findOrderByNo(String orderNo);
  @Select(ORDER_SELECT + " WHERE \"userId\"=#{userId} ORDER BY \"createdAt\" DESC LIMIT #{limit} OFFSET #{offset}") List<BillingOrderRecord> listOrders(@Param("userId") String userId, @Param("limit") int limit, @Param("offset") int offset);
  @Select("SELECT COUNT(*) FROM \"BillingOrder\" WHERE \"userId\"=#{userId}") long countOrders(String userId);
  @Insert("INSERT INTO \"BillingOrder\" (\"id\",\"orderNo\",\"userId\",\"productId\",\"productCode\",\"productName\",\"quantity\",\"creditAmount\",\"amountMinor\",\"currency\",\"status\",\"provider\",\"idempotencyKey\",\"expiresAt\",\"createdAt\",\"updatedAt\") VALUES (#{id},#{orderNo},#{userId},#{productId},#{productCode},#{productName},#{quantity},#{creditAmount},#{amountMinor},#{currency},'CREATED',#{provider},#{idempotencyKey},#{expiresAt},CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)") int insertOrder(BillingOrderRecord order);
  @Update("UPDATE \"BillingOrder\" SET \"status\"='PAID',\"paidAt\"=CURRENT_TIMESTAMP,\"updatedAt\"=CURRENT_TIMESTAMP WHERE \"orderNo\"=#{orderNo} AND \"status\" IN ('CREATED','PAYING')") int markOrderPaid(String orderNo);
  @Update("UPDATE \"BillingOrder\" SET \"status\"='CANCELLED',\"updatedAt\"=CURRENT_TIMESTAMP WHERE \"orderNo\"=#{orderNo} AND \"userId\"=#{userId} AND \"status\" IN ('CREATED','PAYING')") int cancelOrder(@Param("userId") String userId, @Param("orderNo") String orderNo);
  @Select("SELECT o.\"orderNo\",o.\"userId\",u.\"phone\",o.\"productCode\",o.\"productName\",o.\"quantity\",o.\"creditAmount\",o.\"amountMinor\",o.\"currency\",o.\"status\",o.\"provider\",o.\"expiresAt\",o.\"paidAt\",o.\"createdAt\" FROM \"BillingOrder\" o JOIN \"User\" u ON u.\"id\"=o.\"userId\" WHERE (#{status} IS NULL OR o.\"status\"=#{status}) AND (#{query} IS NULL OR o.\"orderNo\" LIKE CONCAT('%',#{query},'%') OR u.\"phone\" LIKE CONCAT('%',#{query},'%')) ORDER BY o.\"createdAt\" DESC LIMIT #{limit} OFFSET #{offset}") List<AdminBillingOrderRecord> listAdminOrders(@Param("status") String status, @Param("query") String query, @Param("limit") int limit, @Param("offset") int offset);
  @Select("SELECT COUNT(*) FROM \"BillingOrder\" o JOIN \"User\" u ON u.\"id\"=o.\"userId\" WHERE (#{status} IS NULL OR o.\"status\"=#{status}) AND (#{query} IS NULL OR o.\"orderNo\" LIKE CONCAT('%',#{query},'%') OR u.\"phone\" LIKE CONCAT('%',#{query},'%'))") long countAdminOrders(@Param("status") String status, @Param("query") String query);
  @Select("SELECT o.\"orderNo\",o.\"userId\",u.\"phone\",o.\"productCode\",o.\"productName\",o.\"quantity\",o.\"creditAmount\",o.\"amountMinor\",o.\"currency\",o.\"status\",o.\"provider\",o.\"expiresAt\",o.\"paidAt\",o.\"createdAt\" FROM \"BillingOrder\" o JOIN \"User\" u ON u.\"id\"=o.\"userId\" WHERE o.\"orderNo\"=#{orderNo} LIMIT 1") AdminBillingOrderRecord findAdminOrder(String orderNo);
  @Select("SELECT \"id\",\"orderId\",\"provider\",\"providerTransactionId\",\"providerEventId\",\"status\",\"amountMinor\",\"currency\",\"signatureVerified\",\"paidAt\",\"createdAt\" FROM \"PaymentTransaction\" WHERE \"provider\"=#{provider} AND \"providerEventId\"=#{eventId} LIMIT 1") PaymentTransactionRecord findPaymentEvent(@Param("provider") String provider, @Param("eventId") String eventId);
  @Insert("INSERT INTO \"PaymentTransaction\" (\"id\",\"orderId\",\"provider\",\"providerTransactionId\",\"providerEventId\",\"status\",\"amountMinor\",\"currency\",\"signatureVerified\",\"paidAt\",\"createdAt\",\"updatedAt\") VALUES (#{id},#{orderId},#{provider},#{transactionId},#{eventId},'SUCCEEDED',#{amountMinor},#{currency},TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT (\"provider\",\"providerEventId\") DO NOTHING") int insertPayment(@Param("id") String id, @Param("orderId") String orderId, @Param("provider") String provider, @Param("transactionId") String transactionId, @Param("eventId") String eventId, @Param("amountMinor") long amountMinor, @Param("currency") String currency);
  @Insert("INSERT INTO \"CreditProduct\" (\"id\",\"code\",\"name\",\"creditAmount\",\"amountMinor\",\"currency\",\"validityDays\",\"status\",\"sortOrder\",\"createdBy\",\"createdAt\",\"updatedAt\") VALUES (#{product.id},#{product.code},#{product.name},#{product.creditAmount},#{product.amountMinor},#{product.currency},#{product.validityDays},'DRAFT',#{product.sortOrder},#{createdBy},CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)") int insertProduct(@Param("product") CreditProductRecord product, @Param("createdBy") String createdBy);
  @Update("UPDATE \"CreditProduct\" SET \"status\"=#{status},\"updatedAt\"=CURRENT_TIMESTAMP WHERE \"id\"=#{id} AND \"status\"=#{expectedStatus}") int updateProductStatus(@Param("id") String id, @Param("status") String status, @Param("expectedStatus") String expectedStatus);
  @Insert("INSERT INTO \"Refund\" (\"id\",\"orderId\",\"paymentTransactionId\",\"amountMinor\",\"reason\",\"status\",\"idempotencyKey\",\"createdBy\",\"createdAt\") VALUES (#{id},#{orderId},#{paymentTransactionId},#{amountMinor},#{reason},'REQUESTED',#{idempotencyKey},#{createdBy},CURRENT_TIMESTAMP)") int insertRefund(RefundRecord refund);
  @Select("SELECT \"id\",\"orderId\",\"paymentTransactionId\",\"amountMinor\",\"reason\",\"status\",\"providerRefundId\",\"idempotencyKey\",\"createdBy\",\"createdAt\",\"completedAt\" FROM \"Refund\" WHERE \"idempotencyKey\"=#{key} LIMIT 1") RefundRecord findRefundByKey(String key);
  @Update("UPDATE \"Refund\" SET \"status\"='SUCCEEDED',\"providerRefundId\"=#{providerRefundId},\"completedAt\"=CURRENT_TIMESTAMP WHERE \"id\"=#{id} AND \"status\"='REQUESTED'") int markRefundSucceeded(@Param("id") String id, @Param("providerRefundId") String providerRefundId);
  @Update("UPDATE \"BillingOrder\" SET \"status\"='REFUNDED',\"updatedAt\"=CURRENT_TIMESTAMP WHERE \"orderNo\"=#{orderNo} AND \"status\"='PAID'") int markOrderRefunded(String orderNo);
  @Select("SELECT \"id\",\"actorId\",\"actorType\",\"action\",\"subjectType\",\"subjectId\",\"beforeJson\",\"afterJson\",\"reason\",\"createdAt\" FROM \"BillingAuditEvent\" WHERE (#{subjectType} IS NULL OR \"subjectType\"=#{subjectType}) AND (#{subjectId} IS NULL OR \"subjectId\"=#{subjectId}) ORDER BY \"createdAt\" DESC LIMIT #{limit} OFFSET #{offset}") List<BillingAuditRecord> listAudit(@Param("subjectType") String subjectType, @Param("subjectId") String subjectId, @Param("limit") int limit, @Param("offset") int offset);
  @Select("SELECT COUNT(*) FROM \"BillingAuditEvent\" WHERE (#{subjectType} IS NULL OR \"subjectType\"=#{subjectType}) AND (#{subjectId} IS NULL OR \"subjectId\"=#{subjectId})") long countAudit(@Param("subjectType") String subjectType, @Param("subjectId") String subjectId);
}
