<script setup lang="ts">
import { onMounted, ref } from "vue";
import { api, type BillingAccount, type BillingLedgerItem, type BillingOrder, type BillingProduct } from "@/api/client";
import InspirationShell from "@/layouts/InspirationShell.vue";
const account = ref<BillingAccount | null>(null); const items = ref<BillingLedgerItem[]>([]); const error = ref(""); const loading = ref(true);
const products = ref<BillingProduct[]>([]); const orders = ref<BillingOrder[]>([]); const buying = ref("");
async function load() { const [a, l, p, o] = await Promise.all([api.account.account(), api.account.ledger(), api.account.products(), api.account.orders()]); account.value = a.account; items.value = l.items; products.value = p; orders.value = o.items; }
async function buy(product: BillingProduct) { buying.value = product.id; error.value = ""; try { await api.account.createOrder({ productId: product.id, quantity: 1, provider: "mock", idempotencyKey: `web-${product.id}-${Date.now()}` }); await load(); } catch (e) { error.value = e instanceof Error ? e.message : "订单创建失败"; } finally { buying.value = ""; } }
onMounted(async () => { try { await load(); } catch (e) { error.value = e instanceof Error ? e.message : "加载失败"; } finally { loading.value = false; } });
</script>
<template><InspirationShell><section class="account-page"><header class="page-heading"><p class="eyebrow">ACCOUNT</p><h1>账户与额度</h1><p>查看额度余额、流水和支付订单。</p></header><p v-if="loading">加载中...</p><p v-else-if="error" class="error-text">{{ error }}</p><template v-else><div class="account-summary"><strong>{{ account?.available ?? 0 }}</strong><span>可用额度 / 共 {{ account?.total ?? 0 }} 点</span><small>{{ account?.status === 'ACTIVE' ? '账号正常' : '账号已限制新操作' }}</small></div><section class="ledger-section"><h2>购买额度</h2><div class="product-list"><article v-for="product in products" :key="product.id"><strong>{{ product.name }}</strong><span>{{ product.creditAmount }} 点 · {{ (product.amountMinor / 100).toFixed(2) }} {{ product.currency }}</span><button type="button" :disabled="buying === product.id" @click="buy(product)">{{ buying === product.id ? '创建中...' : '创建订单' }}</button></article><p v-if="!products.length">暂无可购买产品</p></div></section><section class="ledger-section"><h2>额度流水</h2><p v-if="!items.length">暂无流水</p><table v-else><thead><tr><th>时间</th><th>类型</th><th>点数</th><th>余额</th><th>来源</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td>{{ new Date(item.createdAt).toLocaleString() }}</td><td>{{ item.type }}</td><td>{{ item.amount }}</td><td>{{ item.balanceAfter }}</td><td>{{ item.sourceType || '-' }}</td></tr></tbody></table></section><section class="ledger-section"><h2>支付订单</h2><p v-if="!orders.length">暂无订单</p><table v-else><thead><tr><th>订单号</th><th>产品</th><th>金额</th><th>状态</th></tr></thead><tbody><tr v-for="order in orders" :key="order.orderNo"><td>{{ order.orderNo }}</td><td>{{ order.productName }} × {{ order.quantity }}</td><td>{{ (order.amountMinor / 100).toFixed(2) }} {{ order.currency }}</td><td>{{ order.status }}</td></tr></tbody></table></section></template></section></InspirationShell></template>
