<script setup lang="ts">
import { ArrowUp, Check, ChevronDown, ChevronUp, Copy, Download, Ellipsis, Heart, Image, ImagePlus, Plus, RefreshCw, X } from "lucide-vue-next";
import { computed, onMounted, ref, watch } from "vue";
import { RouterLink, useRoute, useRouter } from "vue-router";
import { api, type Inspiration } from "@/api/client";
import { fixtureInspirations } from "@/api/fixtures";
import InspirationShell from "@/layouts/InspirationShell.vue";
import { useAuthStore } from "@/stores/auth";
import { usePreferencesStore } from "@/stores/preferences";

const route = useRoute(); const router = useRouter(); const auth = useAuthStore(); const preferences = usePreferencesStore(); const inspiration = ref<Inspiration | null>(null); const loading = ref(true); const error = ref(""); const copied = ref(false); const liked = ref(false); const following = ref(false); const composer = ref<"same" | "reference" | null>(null); const prompt = ref("");
const index = computed(() => fixtureInspirations.findIndex((item) => item.slug === inspiration.value?.slug)); const previous = computed(() => index.value > 0 ? fixtureInspirations[index.value - 1] : null); const next = computed(() => index.value >= 0 && index.value < fixtureInspirations.length - 1 ? fixtureInspirations[index.value + 1] : null);
const text = computed(() => preferences.language === "zh" ? { close: "关闭详情", previous: "上一个作品", next: "下一个作品", follow: "+ 关注", followed: "已关注", like: "点赞", more: "更多", ai: "内容由 AI 生成", prompt: "图片提示词", same: "做同款", reference: "用作参考图", copy: "复制提示词", copied: "已复制", download: "下载图片", generate: "图片生成", submit: "提交生成", failed: "作品不存在或暂时无法加载" } : { close: "Close detail", previous: "Previous work", next: "Next work", follow: "+ Follow", followed: "Following", like: "Like", more: "More", ai: "AI-generated content", prompt: "Image prompt", same: "Recreate", reference: "Use as reference", copy: "Copy prompt", copied: "Copied", download: "Download image", generate: "Image generation", submit: "Submit generation", failed: "This work is unavailable" });
async function load() { loading.value = true; error.value = ""; const slug = String(route.params.slug); try { inspiration.value = await api.inspiration(slug); } catch { inspiration.value = fixtureInspirations.find((item) => item.slug === slug) || null; if (!inspiration.value) error.value = text.value.failed; } if (inspiration.value) prompt.value = inspiration.value.prompt; loading.value = false; }
async function copyPrompt() { if (!inspiration.value) return; try { await navigator.clipboard.writeText(inspiration.value.prompt); copied.value = true; window.setTimeout(() => copied.value = false, 1600); } catch { error.value = preferences.language === "zh" ? "复制失败，请手动选择提示词" : "Copy failed. Select the prompt manually."; } }
function openComposer(mode: "same" | "reference") { if (!inspiration.value) return; composer.value = mode; prompt.value = inspiration.value.prompt; }
function submit() { if (!inspiration.value) return; const intent = { returnTo: "/generate", action: "generate", draft: { prompt: prompt.value, model: inspiration.value.modelName, ratio: inspiration.value.ratio, resolution: inspiration.value.resolutionLabel, referenceImageUrl: composer.value === "reference" ? inspiration.value.imageUrl : null } }; sessionStorage.setItem("dream-space-pending-auth-intent", JSON.stringify(intent)); if (!auth.session?.authenticated) { router.push({ path: "/login", query: { returnTo: "/generate" } }); return; } router.push("/generate"); }
watch(() => route.params.slug, load); onMounted(load);
</script>

<template>
  <InspirationShell>
    <div v-if="loading" class="generation-loading">Loading...</div>
    <section v-else-if="error || !inspiration" class="empty-state" role="alert"><div><strong>{{ error || text.failed }}</strong><RouterLink class="action-btn" to="/inspiration">{{ text.close }}</RouterLink></div></section>
    <template v-else>
      <div class="detail-layout" :class="{ 'has-detail-composer': composer }">
        <section class="detail-stage" aria-label="Artwork image"><img class="detail-image" :src="inspiration.imageUrl" :alt="inspiration.title" :width="inspiration.width" :height="inspiration.height" /><RouterLink class="icon-btn detail-close" to="/inspiration" :aria-label="text.close"><X aria-hidden="true" /></RouterLink><div class="pager"><button class="icon-btn" type="button" :disabled="!previous" :aria-label="text.previous" @click="previous && router.push(`/inspiration/${previous.slug}`)"><ChevronUp aria-hidden="true" /></button><button class="icon-btn" type="button" :disabled="!next" :aria-label="text.next" @click="next && router.push(`/inspiration/${next.slug}`)"><ChevronDown aria-hidden="true" /></button></div></section>
        <aside class="detail-panel"><div class="author-line"><div class="avatar">{{ inspiration.authorDisplayName.slice(0, 1).toUpperCase() }}</div><strong>{{ inspiration.authorDisplayName }}</strong><button class="follow-btn" :class="{ active: following }" type="button" @click="following = !following">{{ following ? text.followed : text.follow }}</button><div class="panel-actions"><button class="icon-btn" :class="{ active: liked }" type="button" :aria-label="text.like" @click="liked = !liked"><Heart :fill="liked ? 'currentColor' : 'none'" aria-hidden="true" /></button><span>{{ inspiration.likeCount + (liked ? 1 : 0) }}</span><button class="icon-btn" type="button" :aria-label="text.more"><Ellipsis aria-hidden="true" /></button></div></div><p class="detail-copy">{{ inspiration.title }}</p><p class="detail-date">{{ inspiration.publishedAt || '2026-07-31' }} · {{ text.ai }}</p><div class="prompt-label">{{ text.prompt }}</div><p class="prompt-text">{{ inspiration.prompt }}</p><div class="param-line"><span>{{ inspiration.modelName }}</span><span>|</span><span>{{ inspiration.ratio }}</span><span>|</span><span>{{ inspiration.resolutionLabel }}</span></div><div class="detail-actions"><button class="action-btn" type="button" @click="openComposer('same')"><RefreshCw aria-hidden="true" />{{ text.same }}</button><button class="action-btn" type="button" @click="openComposer('reference')"><ImagePlus aria-hidden="true" />{{ text.reference }}</button><button class="action-btn" type="button" @click="copyPrompt"> <Check v-if="copied" aria-hidden="true" /><Copy v-else aria-hidden="true" />{{ copied ? text.copied : text.copy }}</button><a class="action-btn" :href="inspiration.imageUrl" download><Download aria-hidden="true" />{{ text.download }}</a></div></aside>
      </div>
      <section v-if="composer" class="composer detail-composer" aria-label="Quick composer"><div v-if="composer === 'reference'" class="ref-strip"><span class="reference-thumb"><img :src="inspiration.thumbnailUrl" alt="" /><button type="button" aria-label="删除参考图" @click="composer = 'same'"><X aria-hidden="true" /></button></span></div><div class="prompt-row"><button class="upload-btn" type="button" aria-label="添加参考图"><Plus aria-hidden="true" /></button><textarea v-model="prompt" aria-label="Prompt" /></div><div class="composer-footer"><button class="field-btn" type="button"><Image aria-hidden="true" />{{ text.generate }}</button><button class="field-btn" type="button">{{ inspiration.modelName }}</button><button class="field-btn" type="button">{{ inspiration.ratio }}</button><button class="field-btn" type="button">{{ inspiration.resolutionLabel }}</button><button class="submit-btn" type="button" :disabled="!prompt.trim()" :aria-label="text.submit" @click="submit"><ArrowUp aria-hidden="true" /></button></div></section>
    </template>
  </InspirationShell>
</template>
